# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "⬆️ Bump pre-commit hooks"
  autoupdate_schedule: quarterly
  autofix_commit_msg: "🎨 Incorporated pre-commit fixes"

exclude: "^(libs/|docs/examples/i10\\.aig$)"

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Handle unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  # Check for spelling
  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos

  # Check for common RST mistakes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Python linting using ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  # Check static types with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^(bindings/aigverse|noxfile.py)
        args: []
        additional_dependencies:
          - nox
          - pytest

  # clang-format the C++ part of the code base
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ["-style=file"]

  # Clean jupyter notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - raw_mimetype
          - --

  # Also run Black on examples in the documentation
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.*]

  # Format configuration files with prettier
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  # Check JSON schemata
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs

  # Check the pyproject.toml file
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2025.04.07
    hooks:
      - id: validate-pyproject
