"""Input/Output functionality."""

import os

import aigverse.networks

def read_aiger_into_aig(filename: str | os.PathLike) -> aigverse.networks.NamedAig: ...
def read_ascii_aiger_into_aig(filename: str | os.PathLike) -> aigverse.networks.NamedAig: ...
def read_aiger_into_sequential_aig(filename: str | os.PathLike) -> aigverse.networks.SequentialAig: ...
def read_ascii_aiger_into_sequential_aig(filename: str | os.PathLike) -> aigverse.networks.SequentialAig: ...
def write_aiger(ntk: aigverse.networks.Aig, filename: str | os.PathLike) -> None: ...
def read_pla_into_aig(filename: str | os.PathLike) -> aigverse.networks.Aig: ...
def read_verilog_into_aig(filename: str | os.PathLike) -> aigverse.networks.NamedAig: ...
def write_verilog(ntk: aigverse.networks.Aig, filename: str | os.PathLike) -> None: ...
def write_dot(ntk: aigverse.networks.Aig, filename: str | os.PathLike) -> None: ...
