import os

from . import networks

def read_aiger_into_aig(filename: str | os.PathLike[str]) -> networks.NamedAig: ...
def read_ascii_aiger_into_aig(filename: str | os.PathLike[str]) -> networks.NamedAig: ...
def read_aiger_into_sequential_aig(filename: str | os.PathLike[str]) -> networks.SequentialAig: ...
def read_ascii_aiger_into_sequential_aig(filename: str | os.PathLike[str]) -> networks.SequentialAig: ...
def read_pla_into_aig(filename: str | os.PathLike[str]) -> networks.Aig: ...
def read_verilog_into_aig(filename: str | os.PathLike[str]) -> networks.NamedAig: ...
def write_aiger(ntk: networks.Aig, filename: str | os.PathLike[str]) -> None: ...
def write_verilog(ntk: networks.Aig, filename: str | os.PathLike[str]) -> None: ...
def write_dot(ntk: networks.Aig, filename: str | os.PathLike[str]) -> None: ...
