"""Logic network data structures."""

from collections.abc import Iterator, Sequence
from typing import overload

class AigSignal:
    def __init__(self, index: int, complement: bool) -> None: ...
    def get_index(self) -> int: ...
    def get_complement(self) -> bool: ...
    def get_data(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, arg: object, /) -> bool: ...
    def __ne__(self, arg: object, /) -> bool: ...
    def __lt__(self, arg: AigSignal, /) -> bool: ...
    def __invert__(self) -> AigSignal: ...
    def __pos__(self) -> AigSignal: ...
    def __neg__(self) -> AigSignal: ...
    def __xor__(self, arg: bool, /) -> AigSignal: ...

class Aig:
    def __init__(self) -> None: ...
    def clone(self) -> Aig: ...
    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def get_node(self, s: AigSignal) -> int: ...
    def make_signal(self, n: int) -> AigSignal: ...
    def is_complemented(self, s: AigSignal) -> bool: ...
    def node_to_index(self, n: int) -> int: ...
    def index_to_node(self, index: int) -> int: ...
    def pi_index(self, n: int) -> int: ...
    def pi_at(self, index: int) -> int: ...
    def po_index(self, s: AigSignal) -> int: ...
    def po_at(self, index: int) -> AigSignal: ...
    def get_constant(self, value: bool) -> AigSignal: ...
    def create_pi(self) -> AigSignal: ...
    def create_po(self, f: AigSignal) -> int: ...
    def is_combinational(self) -> bool: ...
    def create_buf(self, a: AigSignal) -> AigSignal: ...
    def create_not(self, a: AigSignal) -> AigSignal: ...
    def create_and(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_nand(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_or(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_nor(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_xor(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_xnor(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_lt(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_le(self, a: AigSignal, b: AigSignal) -> AigSignal: ...
    def create_maj(self, a: AigSignal, b: AigSignal, c: AigSignal) -> AigSignal: ...
    def create_ite(self, cond: AigSignal, f_then: AigSignal, f_else: AigSignal) -> AigSignal: ...
    def create_xor3(self, a: AigSignal, b: AigSignal, c: AigSignal) -> AigSignal: ...
    def create_nary_and(self, fs: Sequence[AigSignal]) -> AigSignal: ...
    def create_nary_or(self, fs: Sequence[AigSignal]) -> AigSignal: ...
    def create_nary_xor(self, fs: Sequence[AigSignal]) -> AigSignal: ...
    def clone_node(self, other: Aig, source: int, children: Sequence[AigSignal]) -> AigSignal: ...
    def nodes(self) -> list[int]: ...
    def gates(self) -> list[int]: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[AigSignal]: ...
    def fanins(self, n: int) -> list[AigSignal]: ...
    def fanin_size(self, n: int) -> int: ...
    def fanout_size(self, n: int) -> int: ...
    def is_constant(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def has_and(self, a: AigSignal, b: AigSignal) -> AigSignal | None: ...
    def is_and(self, n: int) -> bool: ...
    def is_or(self, n: int) -> bool: ...
    def is_xor(self, n: int) -> bool: ...
    def is_maj(self, n: int) -> bool: ...
    def is_ite(self, n: int) -> bool: ...
    def is_xor3(self, n: int) -> bool: ...
    def is_nary_and(self, n: int) -> bool: ...
    def is_nary_or(self, n: int) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, arg: object, /) -> None: ...
    def cleanup_dangling(self) -> None: ...

class NamedAig(Aig):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ntk: NamedAig) -> None: ...
    @overload
    def __init__(self, ntk: Aig) -> None: ...
    def create_pi(self, name: str = "") -> AigSignal: ...
    def create_po(self, f: AigSignal, name: str = "") -> int: ...
    def set_network_name(self, name: str) -> None: ...
    def get_network_name(self) -> str: ...
    def has_name(self, s: AigSignal) -> bool: ...
    def set_name(self, s: AigSignal, name: str) -> None: ...
    def get_name(self, s: AigSignal) -> str: ...
    def has_output_name(self, index: int) -> bool: ...
    def set_output_name(self, index: int, name: str) -> None: ...
    def get_output_name(self, index: int) -> str: ...

class DepthAig(Aig):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ntk: DepthAig) -> None: ...
    @overload
    def __init__(self, ntk: Aig) -> None: ...
    def num_levels(self) -> int: ...
    def level(self, n: int) -> int: ...
    def is_on_critical_path(self, n: int) -> bool: ...
    def update_levels(self) -> None: ...
    def create_po(self, f: AigSignal) -> int: ...

class FanoutAig(Aig):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ntk: Aig) -> None: ...
    @overload
    def __init__(self, ntk: FanoutAig) -> None: ...
    def fanouts(self, n: int) -> list[int]: ...

class AigRegister:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, register: AigRegister) -> None: ...
    @property
    def control(self) -> str: ...
    @control.setter
    def control(self, arg: str, /) -> None: ...
    @property
    def init(self) -> int: ...
    @init.setter
    def init(self, arg: int, /) -> None: ...
    @property
    def type(self) -> str: ...
    @type.setter
    def type(self, arg: str, /) -> None: ...

class SequentialAig(Aig):
    def __init__(self) -> None: ...
    def create_pi(self) -> AigSignal: ...
    def create_po(self, f: AigSignal) -> int: ...
    def create_ro(self) -> AigSignal: ...
    def create_ri(self, f: AigSignal) -> int: ...
    def is_combinational(self) -> bool: ...
    def is_ci(self, n: int) -> bool: ...
    def is_pi(self, n: int) -> bool: ...
    def is_ro(self, n: int) -> bool: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def num_cis(self) -> int: ...
    def num_cos(self) -> int: ...
    def num_registers(self) -> int: ...
    def pi_at(self, index: int) -> int: ...
    def po_at(self, index: int) -> AigSignal: ...
    def ci_at(self, index: int) -> int: ...
    def co_at(self, index: int) -> AigSignal: ...
    def ro_at(self, index: int) -> int: ...
    def ri_at(self, index: int) -> AigSignal: ...
    def set_register(self, index: int, reg: AigRegister) -> None: ...
    def register_at(self, index: int) -> AigRegister: ...
    def pi_index(self, n: int) -> int: ...
    def ci_index(self, n: int) -> int: ...
    def co_index(self, s: AigSignal) -> int: ...
    def ro_index(self, n: int) -> int: ...
    def ri_index(self, s: AigSignal) -> int: ...
    def ro_to_ri(self, s: AigSignal) -> AigSignal: ...
    def ri_to_ro(self, s: AigSignal) -> int: ...
    def pis(self) -> list[int]: ...
    def pos(self) -> list[AigSignal]: ...
    def cis(self) -> list[int]: ...
    def cos(self) -> list[AigSignal]: ...
    def ros(self) -> list[int]: ...
    def ris(self) -> list[AigSignal]: ...
    def registers(self) -> list[tuple[AigSignal, int]]: ...

class AigEdge:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, source: int, target: int, weight: int = 0) -> None: ...
    @property
    def source(self) -> int: ...
    @source.setter
    def source(self, arg: int, /) -> None: ...
    @property
    def target(self) -> int: ...
    @target.setter
    def target(self, arg: int, /) -> None: ...
    @property
    def weight(self) -> int: ...
    @weight.setter
    def weight(self, arg: int, /) -> None: ...
    def __eq__(self, arg: object, /) -> bool: ...
    def __ne__(self, arg: object, /) -> bool: ...

class AigEdgeList:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, ntk: Aig) -> None: ...
    @overload
    def __init__(self, edges: Sequence[AigEdge]) -> None: ...
    @overload
    def __init__(self, ntk: Aig, edges: Sequence[AigEdge]) -> None: ...
    @property
    def ntk(self) -> Aig: ...
    @ntk.setter
    def ntk(self, arg: Aig, /) -> None: ...
    @property
    def edges(self) -> list[AigEdge]: ...
    @edges.setter
    def edges(self, arg: Sequence[AigEdge], /) -> None: ...
    def append(self, edge: AigEdge) -> None: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Iterator[AigEdge]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, arg: int, /) -> AigEdge: ...
    def __setitem__(self, arg0: int, arg1: AigEdge, /) -> None: ...

@overload
def to_edge_list(ntk: SequentialAig, regular_weight: int = 0, inverted_weight: int = 1) -> AigEdgeList: ...
@overload
def to_edge_list(ntk: Aig, regular_weight: int = 0, inverted_weight: int = 1) -> AigEdgeList: ...

class AigIndexList:
    @overload
    def __init__(self, num_pis: int = 0) -> None: ...
    @overload
    def __init__(self, values: Sequence[int]) -> None: ...
    def raw(self) -> list[int]: ...
    def size(self) -> int: ...
    def num_gates(self) -> int: ...
    def num_pis(self) -> int: ...
    def num_pos(self) -> int: ...
    def add_inputs(self, n: int = 1) -> None: ...
    def add_and(self, lit0: int, lit1: int) -> int: ...
    def add_xor(self, lit0: int, lit1: int) -> int: ...
    def add_output(self, lit: int) -> None: ...
    def clear(self) -> None: ...
    def gates(self) -> list[tuple[int, int]]: ...
    def pos(self) -> list[int]: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, arg: int, /) -> int: ...
    def __setitem__(self, arg0: int, arg1: int, /) -> None: ...
    def __len__(self) -> int: ...

def to_index_list(ntk: Aig) -> AigIndexList: ...
def to_aig(il: AigIndexList) -> Aig: ...
