# this file is heavily based on https://github.com/cda-tum/mqt-workflows/blob/main/.github/workflows/reusable-python-ci.yml

name: 🐍 • CI

on:
  merge_group:
  push:
    branches: ["main"]
    paths:
      - "src/aigverse/**"
      - "test/**"
      - "**/*.py"
      - "**/*.pyi"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - "libs/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/aigverse-python-tests.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "src/aigverse/**"
      - "test/**"
      - "**/*.py"
      - "**/*.pyi"
      - "**/*.hpp"
      - "**/*.cpp"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - "libs/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/aigverse-python-tests.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🚨 Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Run ty
        run: uvx prek run -a ty

      - name: Check if stub files are up to date
        run: |
          uvx nox -s stubs
          if [[ -n "$(git status --porcelain python)" ]]; then
            echo "Stub files are not up to date. Please run 'nox -s stubs' and commit the changes."
            git --no-pager diff python
            exit 1
          fi

      - name: Run check-sdist
        run: uvx check-sdist --inject-junk

  python-tests:
    name: 🐍 ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, windows-2025]
    steps:
      - name: Clone Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2
        with:
          key: "${{matrix.runs-on}}-aigverse"
          save: true
          max-size: 10G

      - if: runner.os == 'Linux'
        name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: 🐍 Test
        run: uvx nox -s tests --verbose
