name: 📦 • Build sdist

on:
  workflow_call:

permissions: {}

jobs:
  build_sdist:
    name: 📦 Build Source Distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read # required to check out the repository
    steps:
      - name: Clone Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: false

      - name: Build sdist
        run: uv build --sdist

      - name: Check metadata
        run: uvx twine check dist/*

      - name: Upload sdist as an artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          overwrite: true
