name: Clang-Tidy Review

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/clang-tidy-review.yml"
  push:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/clang-tidy-review.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  clangtidy:
    runs-on: ubuntu-latest
    name: 🚨 Clang-Tidy

    steps:
      - name: Clone Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libpython3-dev

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7.5.0

      - name: Install build dependencies with uv
        run: uv sync --only-group build --no-install-project

      - name: Generate compilation database
        run: >
          cmake -B build -S .
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DPython_EXECUTABLE=${{ github.workspace }}/.venv/bin/python

      - name: Run clang-tidy
        id: linter
        uses: cpp-linter/cpp-linter-action@24467985494bed9bfc398489b6ec12469beaf4da # v2.17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ""
          tidy-checks: ""
          database: "build"
          step-summary: true
          thread-comments: ${{ ((github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork) && 'update') || 'false' }}
          ignore: "build|libs/*|docs/*"
          extra-args: "-I${{ github.workspace }}/include -I${{ github.workspace }}/src/aigverse"
          version: "21"
          files-changed-only: true

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
