name: Clang-Tidy Review

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/clang-tidy-review.yml"
  push:
    branches: ["main"]
    paths:
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/clang-tidy-review.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  clangtidy:
    runs-on: ubuntu-latest
    name: 🚨 Clang-Tidy

    steps:
      - name: Clone Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libpython3-dev

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Install build dependencies with uv
        run: uv sync --only-group build --no-install-project

      - name: Generate compilation database
        run: >
          cmake -B build -S .
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DPython_EXECUTABLE=${{ github.workspace }}/.venv/bin/python

      - name: Run clang-tidy
        id: linter
        uses: cpp-linter/cpp-linter-action@77c390c5ba9c947ebc185a3e49cc754f1558abb5 # v2.18.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ""
          tidy-checks: ""
          database: "build"
          step-summary: true
          thread-comments: ${{ ((github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork) && 'update') || 'false' }}
          ignore: "build|libs/*|docs/*"
          extra-args: "-I${{ github.workspace }}/include -I${{ github.workspace }}/src/aigverse"
          version: "21"
          files-changed-only: true

      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
