name: 📝 • Release Drafter

on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  update_release_draft:
    name: 📝 Draft the next release
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create and update the release draft

    steps:
      - name: Draft the release notes 📝
        uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
